Add config to disable feature and added relative './' parsing

diff --git a/give-control b/give-control
--- a/give-control
+++ b/give-control
@@ -1,6 +1,7 @@
 #!/bin/sh
 # ******************* config *********************
 Enable_Setting='kTCCServiceAccessibility'
+Do_Enable=true
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 if [[ "$1" =~ ^~ ]]
@@ -10,8 +11,18 @@ then
 elif [[ "$1" =~ ^/ ]]
 then
 	f="$1"
+elif [[ "$1" =~ ^./ ]]
+then
+        /bin/sh $0 $(echo "$1" | cut -c 3-)
+        exit $?
 else
 	f="$(pwd)/$1"
+fi
+cat "$f" 2> /dev/null > /dev/null
+if [ $? -ne 0 ]
+then
+	echo "File $f not found"
+	exit 1
 fi
 REQ_HEX="0"
 echo "true" > /tmp/nonsgn.dat
@@ -29,9 +40,11 @@ $(cat /tmp/nonsgn.dat) &&\
 echo "$f"
 echo "$REQ_HEX"
 __DATE=$(date +%s)
+__AUTHVAL=0
+$Do_Enable && __AUTHVAL=2
 sudo sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db "
         DELETE FROM \"access\" where client = '$f' and service = '$Enable_Setting';
         DELETE FROM \"access\" where csreq = X'$REQ_HEX' and service = '$Enable_Setting';
-        INSERT INTO \"access\" VALUES('$Enable_Setting','$f',$__NUM,2,4,1,X'$REQ_HEX',NULL,0,0,NULL,0,$__DATE,NULL,NULL,'',$__DATE)
+        INSERT INTO \"access\" VALUES('$Enable_Setting','$f',$__NUM,$__AUTHVAL,4,1,X'$REQ_HEX',NULL,0,0,NULL,0,$__DATE,NULL,NULL,'',$__DATE)
 "
 
